version: '3.0'
services:
  sut:
    build: .
    command: bin/setup && bin/rails test && brakeman
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres:10
  redis:
    image: redis:3.2
