default: &default
  adapter: redis
  url: <%= ENV["REDIS_URL"] %>

development:
  <<: *default
  channel_prefix: campo_development

test:
  <<: *default
  channel_prefix: campo_test

production:
  <<: *default
  channel_prefix: campo_production
